
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

light: !include light-groups.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
#automation: !include automations.yaml

script: !include scripts.yaml
scene: !include scenes.yaml

